#!/bin/bash
# File: project_setup
# Desc: Installs required modules and sets Flask variables

pip install -r MovieRecommender/requirements.txt
pip install -r model/requirements.txt
npm install cypress

export FLASK_APP=mov_rec
export FLASK_ENV=development

